services:
  searxng:
    image: searxng/searxng:2026.9.25-12f8b6515
    container_name: searxng
    restart: unless-stopped
    ports:
      - "8088:8080"
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8088/
      - SEARXNG_SECRET=591c096b2f5ebb99bab7e34b3ef6cf605fc28ad8b7ae6ffb00881f4f07534410
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
