#!/usr/bin/env bash
# test-report-engine-liveness — stage gating on a dead engine (#830).
#
# report.sh ran every stage unconditionally. When the engine died partway
# through --full, each remaining stage still ran, failed identically, and landed
# as its own <details> block:
#
#   ## bench.sh output
#   ERROR: service not reachable at .../v1/models
#     Start with: cd compose && docker compose up -d
#   ## bench-agentic.sh output
#   ERROR: service not reachable at .../v1/models
#     Start with: bash scripts/launch.sh
#
# Two blocks that read like two more faults. They are one dead engine, and the
# "Start with:" hints are wrong — the service WAS started, it crashed (#827).
#
# Contract asserted here:
#   1. a healthy run is unchanged: every stage runs, no liveness section
#   2. once the endpoint stops answering, remaining stages are SKIPPED — not
#      run into the same wall — with the causal order stated
#   3. exactly ONE liveness verdict, and it does not tell the user to "just
#      start it" when the service was running and crashed
#   4. the partial report written before the death is preserved, footer included
#   5. never-reachable is a distinct verdict, and THAT one does say how to start
set -euo pipefail

# Force Python's UTF-8 mode (PEP 540) for every python3 this script runs.
# Repo sources are full of unicode (— × → ⚠), and without this a rig on a real
# non-UTF-8 locale (de_DE.iso88591 and friends) decodes reads, stdout AND argv
# with the locale codec, which crashes the launcher/emit paths (#779). Python
# already auto-enables UTF-8 mode for the C/POSIX locale, so this covers the
# case it does NOT: a genuine non-UTF-8, non-C locale. Exported, so child
# processes and nested scripts inherit it. Guarded by test-locale-utf8.sh.
export PYTHONUTF8="${PYTHONUTF8:-1}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# shellcheck source=fixtures/report-harness/report-env.sh
source "${ROOT_DIR}/scripts/tests/fixtures/report-harness/report-env.sh"

fail() { echo "FAIL: $1" >&2; exit 1; }
assert_contains() { [[ "$1" == *"$2"* ]] || { echo "FAIL: missing '$2' in report" >&2; echo "$1" >&2; exit 1; }; }
assert_not_contains() { [[ "$1" != *"$2"* ]] || { echo "FAIL: must NOT contain '$2'" >&2; echo "$1" >&2; exit 1; }; }
count_of() { printf '%s\n' "$1" | command grep -c -F "$2" || true; }

report_env_init "$ROOT_DIR"
trap report_env_cleanup EXIT

seed_stages() {
  report_stage_stub verify-full.sh    0 "All checks passed."
  report_stage_stub verify-stress.sh  0 "All stress / boundary checks passed."
  report_stage_stub soak-test.sh      0 "[soak]   verdict              PASS"
  report_stage_stub bench.sh          0 "decode_TPS mean=200.00"
  report_stage_stub bench-agentic.sh  0 "turn 12 ok"
}

# ── 1. healthy --full: every stage runs, nothing is gated ───────────────────
seed_stages
report_stub_start
report_run --full --no-redact

for s in verify-full.sh verify-stress.sh soak-test.sh bench.sh bench-agentic.sh; do
  report_stage_ran "$s" || fail "healthy run should have executed $s"
done
assert_not_contains "$REPORT_OUT" "## Engine liveness"
assert_not_contains "$REPORT_OUT" "SKIPPED"
[[ "$REPORT_RC" -eq 0 ]] || fail "healthy --full should exit 0, got $REPORT_RC"

# ── 2. engine dies during soak: bench + agentic are skipped, once ───────────
seed_stages
report_stage_stub soak-test.sh 1 "[soak]   verdict              FAIL" "[soak]   errors               7"
report_stage_kills_engine soak-test.sh
report_run --full --no-redact

report_stage_ran verify-full.sh   || fail "verify-full should still have run"
report_stage_ran verify-stress.sh || fail "verify-stress should still have run"
report_stage_ran soak-test.sh     || fail "soak should still have run"
report_stage_ran bench.sh         && fail "bench must NOT run after the engine died"
report_stage_ran bench-agentic.sh && fail "bench-agentic must NOT run after the engine died"

# The causal order is stated, and the pre-death report is intact.
assert_contains "$REPORT_OUT" "stopped answering after **soak-test.sh**"
assert_contains "$REPORT_OUT" "## bench.sh output"
assert_contains "$REPORT_OUT" "## bench-agentic.sh output"
assert_contains "$REPORT_OUT" "SKIPPED"
assert_contains "$REPORT_OUT" "## verify-full.sh output"
assert_contains "$REPORT_OUT" "[soak]   verdict              FAIL"
assert_contains "$REPORT_OUT" "_Generated by \`bash scripts/report.sh\`"

# ONE verdict, not one per stage — and it must not be the misleading advice.
[[ "$(count_of "$REPORT_OUT" '## Engine liveness')" -eq 1 ]] \
  || fail "expected exactly one Engine liveness section"
assert_contains "$REPORT_OUT" "The engine died during this run"
assert_contains "$REPORT_OUT" "do not \"just start it\" without reading"
assert_not_contains "$REPORT_OUT" "service not reachable"
assert_not_contains "$REPORT_OUT" "Start with: cd compose"
[[ "$REPORT_RC" -ne 0 ]] || fail "a run with a dead engine must not exit 0"

# ── 3. never reachable: distinct verdict, and here "start it" IS right ──────
seed_stages
report_stub_stop
rm -f "$REPORT_ALIVE_FILE"
report_stub_start
report_run --full --no-redact

for s in verify-full.sh verify-stress.sh soak-test.sh bench.sh bench-agentic.sh; do
  report_stage_ran "$s" && fail "$s must not run when the endpoint was never reachable"
done
assert_contains "$REPORT_OUT" "The endpoint was never reachable"
assert_contains "$REPORT_OUT" "bash scripts/launch.sh"
assert_not_contains "$REPORT_OUT" "The engine died during this run"
[[ "$(count_of "$REPORT_OUT" '## Engine liveness')" -eq 1 ]] \
  || fail "expected exactly one Engine liveness section"

# ── 4. no probe available → gating is inert, never a false "dead" ───────────
# With no URL and no docker, report.sh cannot resolve an endpoint. It must run
# the stages exactly as before rather than inventing an engine death.
report_stub_stop
: > "$REPORT_ALIVE_FILE"
seed_stages
report_run_unprobeable --bench --no-redact
report_stage_ran bench.sh || fail "bench must still run when no endpoint can be probed"
assert_not_contains "$REPORT_OUT" "## Engine liveness"

echo "PASS: test-report-engine-liveness"
