#!/usr/bin/env bash
# dsh-setup.sh — point dsh (DeepSeek Harness, @deepseek-ai/dsh) at this rig's local
# models, through the LiteLLM gateway.
#
#   bash scripts/dsh-setup.sh                    # write/refresh the `club` block in the headless + web profiles
#   bash scripts/dsh-setup.sh --print            # show the block, change nothing
#   bash scripts/dsh-setup.sh --profile headless # one profile (repeatable; default: headless and web)
#   bash scripts/dsh-setup.sh --gateway http://gateway-host:4000/v1   # a gateway on another box
#
# WHAT IT WRITES — one marked block in each profile's cordis.patch.yml
# ($DSH_HOME/profiles/<name>/, DSH_HOME defaults to ~/.dsh):
#   - an llm-pi-ai `club` provider on the gateway. dsh has no gateway discovery, so
#     the model list is a SNAPSHOT: every route the gateway serves right now, with
#     the context window it reports, plus `qwen3.8-27b` (the id every Qwen3.8 slug
#     serves). Re-run it after switching to a slug with a different window or model.
#   - agent-default-model club/qwen3.8-27b at effort low — ONLY when the profile
#     names no default model of its own. A missing profile is created first with
#     `dsh --profile <name> --dump-config` (no model call), so the default is in
#     place before dsh's first run; without it, that run goes to dsh's built-in
#     default, DeepSeek's paid API.
# The rest of the file is never touched, the old file is backed up, and a profile
# whose file already has an llm-pi-ai entry of its own is refused.
#
# THE KEY — the gateway's LITELLM_MASTER_KEY from your club-3090 settings
# (~/.config/club-3090/secrets.env; `bash scripts/gateway-key.sh rotate` makes one),
# else the public default every install shares; LITELLM_MASTER_KEY set in the shell
# wins. It goes into $DSH_HOME/.env as CLUB3090_GATEWAY_KEY (0600), which dsh reads
# for the provider's apiKeyEnv. Nothing else in that file changes. After a rotate,
# re-run this script. DEEPSEEK_API_KEY and your other dsh settings are left alone.
set -euo pipefail
export PYTHONUTF8="${PYTHONUTF8:-1}"
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

PRINT=0
GATEWAY="http://127.0.0.1:4000/v1"
PROFILES=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --print) PRINT=1; shift ;;
    --gateway) GATEWAY="${2:?--gateway needs a URL}"; shift 2 ;;
    --profile) PROFILES+=("${2:?--profile needs a name}"); shift 2 ;;
    -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "dsh-setup: unknown argument '$1' (see --help)" >&2; exit 2 ;;
  esac
done
[[ ${#PROFILES[@]} -gt 0 ]] || PROFILES=(headless web)
for p in "${PROFILES[@]}"; do
  if ! [[ "$p" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
    echo "dsh-setup: '$p' is not a profile name" >&2; exit 2
  fi
  if [[ "$p" == "desktop" ]]; then
    echo "dsh-setup: the desktop profile belongs to the dsh desktop app; set it up there" >&2; exit 2
  fi
done

DSH_HOME_DIR="${DSH_HOME:-$HOME/.dsh}"
# The key through the one settings loader (#1466, #1467).
# shellcheck source=lib/club-config.sh
. "$ROOT_DIR/scripts/lib/club-config.sh"
KEY="$(club_config_get LITELLM_MASTER_KEY "$ROOT_DIR" || true)"
KEY="${KEY:-sk-litellm-master-key}"   # the compose's default, when nothing is stored

if [[ $PRINT -eq 0 ]]; then
  # Create missing profiles the way dsh does, without running a model:
  # --dump-config composes the profile and prints it.
  for p in "${PROFILES[@]}"; do
    [[ -f "$DSH_HOME_DIR/profiles/$p/cordis.patch.yml" ]] && continue
    if ! command -v dsh >/dev/null 2>&1; then
      echo "[dsh-setup] dsh is not on PATH, so the '$p' profile can't be created." >&2
      echo "[dsh-setup]   Install it first: npm install -g @deepseek-ai/dsh" >&2
      exit 1
    fi
    if ! (cd "$HOME" && DSH_HOME="$DSH_HOME_DIR" dsh --profile "$p" --dump-config >/dev/null 2>&1 </dev/null) \
       || [[ ! -f "$DSH_HOME_DIR/profiles/$p/cordis.patch.yml" ]]; then
      echo "[dsh-setup] couldn't create the '$p' profile (dsh --profile $p --dump-config)." >&2
      exit 1
    fi
    echo "[dsh-setup] created the '$p' profile in $DSH_HOME_DIR/profiles/$p (no model was run)"
  done
fi

python3 - "$DSH_HOME_DIR" "$GATEWAY" "$KEY" "$PRINT" "${PROFILES[@]}" <<'PY'
import datetime, io, json, os, re, sys, urllib.request

home, gateway, key, print_only = sys.argv[1], sys.argv[2].rstrip("/"), sys.argv[3], sys.argv[4] == "1"
profiles = sys.argv[5:]
BEGIN = "# >>> club-3090 local models (generated by club-3090 scripts/dsh-setup.sh; re-run to refresh) >>>"
END = "# <<< club-3090 local models <<<"
KEY_NAME = "CLUB3090_GATEWAY_KEY"

# Qwen3.8-family served ids — the same list as scripts/omp-setup.sh, which
# test-omp-setup checks against every name the composes serve (test-dsh-setup
# keeps the two lists equal).
QWEN38_IDS = ["qwen3.8-27b", "qwen3.8-27b-fp8", "thinkingcap38-27b", "thinkingcap38-27b-fp8"]
ALWAYS = "qwen3.8-27b"      # every Qwen3.8 slug serves it, so it is listed even when nothing is up
FALLBACK_WINDOW = 262144    # the dual-fast slugs' window, for an id the gateway isn't serving now
REPLY_CAP = 32768           # thinking + answer; at most half the window on every Qwen3.8 slug
DEFAULT_EFFORT = "low"      # the Qwen3.8 composes' own server default


def live_routes():
    """The gateway's routes that carry model_info (rendered from a serving engine)."""
    root = gateway[:-3] if gateway.endswith("/v1") else gateway
    req = urllib.request.Request(root + "/model_group/info", headers={"Authorization": f"Bearer {key}"})
    try:
        with urllib.request.urlopen(req, timeout=5) as r:
            data = json.load(r).get("data", [])
    except Exception as e:  # noqa: BLE001 — any failure means "no snapshot"
        print(f"[dsh-setup] ⚠️  couldn't read {root}/model_group/info ({e.__class__.__name__}); "
              f"writing {ALWAYS} with a {FALLBACK_WINDOW:,}-token window — re-run with the slug up.",
              file=sys.stderr)
        return {}
    return {g["model_group"]: g for g in data if g.get("model_group") and g.get("max_input_tokens")}


def model_lines(mid, route):
    q = json.dumps  # a JSON string is a valid YAML scalar, whatever the id contains
    out = [f"          - id: {q(mid)}",
           f"            contextWindow: {int(route['max_input_tokens']) if route else FALLBACK_WINDOW}"]
    if mid in QWEN38_IDS:
        # The Qwen3.8 template takes reasoning_effort low | medium | xhigh as a template
        # kwarg — the field both vLLM and SGLang hand to it. With thinkingFormat
        # chat-template, the empty `off` sends enable_thinking: false. Quoted: a YAML 1.1
        # parser (PyYAML) reads a bare off as the boolean false; dsh reads YAML 1.2.
        out += [f"            maxTokens: {REPLY_CAP}",
                "            reasoningEfforts:",
                '              "off":',
                "              low: low",
                "              medium: medium",
                "              xhigh: xhigh",
                "            compat:",
                "              thinkingFormat: chat-template",
                "              chatTemplateKwargs:",
                "                enable_thinking: { $var: thinking.enabled }",
                "                reasoning_effort: { $var: thinking.effort }"]
    elif route and route.get("max_output_tokens"):
        out.append(f"            maxTokens: {int(route['max_output_tokens'])}")
    return out


def block(with_default):
    routes = live_routes.cache
    ids = [ALWAYS] + sorted(k for k in routes if k != ALWAYS)
    lines = [BEGIN,
             "- id: llm-pi-ai",
             "  config:",
             "    providers:",
             "      club:",
             "        displayName: club-3090 local models",
             f"        apiKeyEnv: {KEY_NAME}   # the key itself is in $DSH_HOME/.env",
             "        api: openai-completions",
             f"        baseURL: {json.dumps(gateway)}",
             "        compat:",
             "          supportsDeveloperRole: false",
             "        models:"]
    for mid in ids:
        lines += model_lines(mid, routes.get(mid))
    if with_default:
        lines += ["- id: agent-default-model",
                  "  config:",
                  "    provider: club",
                  f"    model: {ALWAYS}",
                  f"    reasoningEffort: {DEFAULT_EFFORT}"]
    lines.append(END)
    return "\n".join(lines) + "\n"


live_routes.cache = live_routes()

if print_only:
    print(block(True), end="")
    sys.exit(0)

ENTRY = re.compile(r"^-\s*(?:id|name):\s*['\"]?(@deepseek-ai/dsh-)?([A-Za-z0-9._-]+)['\"]?\s*$", re.M)


def foreign_entries(text):
    """Entry ids defined OUTSIDE our marked block."""
    outside = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S)
    return {m.group(2) for m in ENTRY.finditer(outside)}


def backup_and_write(path, old, new, mode):
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    if old:
        bak = f"{path}.bak-{stamp}"
        io.open(bak, "w", encoding="utf-8").write(old)
        os.chmod(bak, mode)
        print(f"[dsh-setup] backed up {path} -> {bak}")
    tmp = path + ".tmp"
    io.open(tmp, "w", encoding="utf-8").write(new)
    os.chmod(tmp, mode)
    os.replace(tmp, path)


failed = []
for name in profiles:
    path = os.path.join(home, "profiles", name, "cordis.patch.yml")
    text = io.open(path, encoding="utf-8").read()
    ours = BEGIN in text and END in text
    foreign = foreign_entries(text)
    if "llm-pi-ai" in foreign:
        failed.append(name)
        print(f"[dsh-setup] {path} already configures llm-pi-ai outside the club-3090 block "
              "(a provider added by hand or in the web UI). Add the club provider there yourself "
              "(docs/CODING_AGENTS.md shows the block), or remove that entry and re-run.", file=sys.stderr)
        continue
    with_default = "agent-default-model" not in foreign
    new_block = block(with_default)
    if ours:
        pre, rest = text.split(BEGIN, 1)
        post = rest.split(END, 1)[1].lstrip("\n")
        new = pre + new_block + post
        action = "refreshed"
    else:
        body = [ln for ln in text.splitlines() if ln.strip() and not ln.lstrip().startswith("#")]
        if body == ["[]"]:
            new = re.sub(r"^\[\]\s*$\n?", lambda _m: new_block, text, count=1, flags=re.M)
        elif body and all(not ln.startswith(("[", "{")) for ln in body) and body[0].startswith("-"):
            new = text.rstrip("\n") + "\n" + new_block
        else:
            failed.append(name)
            print(f"[dsh-setup] {path} is not a top-level YAML list this script can add to — not touching it.",
                  file=sys.stderr)
            continue
        action = "added"
    if new == text:
        print(f"[dsh-setup] {name}: already up to date")
        continue
    backup_and_write(path, text, new, os.stat(path).st_mode & 0o777)
    print(f"[dsh-setup] {action} the club block in the '{name}' profile"
          + ("" if with_default else " (it has its own default model, kept as is)"))

# The key: one line in $DSH_HOME/.env, which dsh reads for apiKeyEnv names.
envp = os.path.join(home, ".env")
old = io.open(envp, encoding="utf-8").read() if os.path.exists(envp) else ""
line = f"{KEY_NAME}={key}"
pat = re.compile(rf"^{KEY_NAME}=.*$", re.M)
new = pat.sub(lambda _m: line, old, count=1) if pat.search(old) else (old.rstrip("\n") + "\n" if old.strip() else "") + line + "\n"
if new != old:
    os.makedirs(home, exist_ok=True)
    backup_and_write(envp, old, new, (os.stat(envp).st_mode & 0o777) if old else 0o600)
    print(f"[dsh-setup] stored the gateway key in {envp} as {KEY_NAME}")

settings = os.path.join(home, "settings.yaml")
if os.path.exists(settings) and re.search(r"^agent-default-model:", io.open(settings, encoding="utf-8").read(), re.M):
    print(f"[dsh-setup] ⚠️  {settings} (from an older dsh) names a default model. dsh moves it into the first "
          "profile it boots, replacing the club default there. Rename it to keep the club default.", file=sys.stderr)

sys.exit(1 if failed else 0)
PY

[[ $PRINT -eq 1 ]] && exit 0

cat <<EOF

Next:
  1. Serve a model:   bash scripts/switch.sh --force vllm/qwen38-27b-dual-fast   (experimental; the slug docs/CODING_AGENTS.md recommends for agents)
  2. Use it:          dsh headless "…"     (or: dsh web — pick club/qwen3.8-27b and its effort in the model menu)
  3. Re-run this script after switching to a slug with a different context window
     or model — dsh keeps the snapshot it was given.
EOF
if ! command -v dsh >/dev/null 2>&1; then
  echo ""
  echo "  (dsh is not on PATH — install it first: npm install -g @deepseek-ai/dsh)"
fi
