#!/usr/bin/env bash
# omp-setup.sh — point omp (oh-my-pi) at this rig's local models, through the
# LiteLLM gateway, with the settings a local GPU needs.
#
#   bash scripts/omp-setup.sh            # write/refresh the `club` provider, print the next steps
#   bash scripts/omp-setup.sh --print    # show the provider block, change nothing
#   bash scripts/omp-setup.sh --gateway http://gateway-host:4000/v1   # a gateway on another box
#
# WHAT IT WRITES — one marked block in ~/.omp/agent/models.yml (or
# $PI_CODING_AGENT_DIR/models.yml): a `club` provider on the LiteLLM gateway
# (:4000) with `discovery: litellm`. The gateway's route set is re-rendered from
# whatever is actually serving on every switch.sh (scripts/lib/litellm-sync.sh),
# and each route carries model_info, so omp sees the live model with its REAL
# context window and output cap — no hand-kept model list, no edit on a switch.
# Other providers in the file are never touched; the old file is backed up.
#
# WHAT IT DOES NOT WRITE — your config.yml. Runtime settings (effort per role,
# append-only context, compaction, artifact spill, subagent concurrency, stream
# timeouts) ship as an overlay, services/omp/omp-club.yml, that you load per run:
#     omp --config <repo>/services/omp/omp-club.yml
# so your own roles and settings stay as they are. docs/CODING_AGENTS.md explains
# every setting and which slug to serve for agent work.
#
# THE KEY — the gateway's LITELLM_MASTER_KEY from your club-3090 settings
# (~/.config/club-3090/secrets.env; `bash scripts/gateway-key.sh rotate` makes one),
# else the public default every install shares. LITELLM_MASTER_KEY set in the shell
# wins (a gateway on another box). After a rotate, re-run this script.
set -euo pipefail
export PYTHONUTF8="${PYTHONUTF8:-1}"
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

PRINT=0
GATEWAY="http://127.0.0.1:4000/v1"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --print) PRINT=1; shift ;;
    --gateway) GATEWAY="${2:?--gateway needs a URL}"; shift 2 ;;
    -h|--help) sed -n '2,27p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "omp-setup: unknown argument '$1' (see --help)" >&2; exit 2 ;;
  esac
done

AGENT_DIR="${PI_CODING_AGENT_DIR:-$HOME/.omp/agent}"
MODELS_YML="$AGENT_DIR/models.yml"
# The key through the one settings loader (#1466, #1467) — never read out of the
# compose file, whose line is `${LITELLM_MASTER_KEY:-…}` now, not the key.
# shellcheck source=lib/club-config.sh
. "$ROOT_DIR/scripts/lib/club-config.sh"
KEY="$(club_config_get LITELLM_MASTER_KEY "$ROOT_DIR" || true)"
KEY="${KEY:-sk-litellm-master-key}"   # the compose's default, when nothing is stored

python3 - "$MODELS_YML" "$GATEWAY" "$KEY" "$PRINT" <<'PY'
import datetime, io, os, re, sys

path, gateway, key, print_only = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4] == "1"
BEGIN = "  # >>> club-3090 local models (generated by club-3090 scripts/omp-setup.sh; re-run to refresh) >>>"
END = "  # <<< club-3090 local models <<<"

# Qwen3.8-family served ids (what the engine's own /v1/models says, not the
# registry's model name). Their chat template takes `reasoning_effort`
# (low | medium | xhigh; it DEFAULTS to xhigh when a request names none) — so omp
# must send the effort on every role; qwenTemplateReasoningEffort puts it in
# chat_template_kwargs, where both vLLM and SGLang pass it to the template.
# Qwen3.8 slugs all serve the shared id `qwen3.8-27b`; the ThinkingCap slugs are
# replicas that serve their OWN name `thinkingcap38-27b` on every tier (fast /
# max / superfast, vLLM and SGLang).
# The FP8 tiers also serve a `-fp8` alias, and the gateway lists every alias as its
# own route, so each needs the override too. test-omp-setup checks this list
# against every name the Qwen3.8-family composes serve.
QWEN38_IDS = ["qwen3.8-27b", "qwen3.8-27b-fp8", "thinkingcap38-27b", "thinkingcap38-27b-fp8"]

def qwen38_override(mid: str) -> str:
    return f"""      {mid}:
        # Reply cap (thinking + answer). The gateway reports it per route, but when
        # it can't (routes rendered before model_info existed, or an engine that
        # reports no context) omp falls back to its catalog's 65,536 — the WHOLE
        # window of the 65K single-card slug. Pinned here, it wins over discovery;
        # 32768 is at most half the window on every Qwen3.8 slug.
        maxTokens: 32768
        # A thinking model on every engine. Stated here because the gateway only
        # says so for slugs that declare a thinking sampler profile; without it omp
        # treats the model as non-reasoning and never sends an effort at all.
        reasoning: true
        thinking:
          mode: effort
          efforts: [low, medium, xhigh]
          defaultLevel: medium
        compat:
          supportsReasoningEffort: true
          qwenTemplateReasoningEffort: true
          # Chat-completions wire only (omp talks Responses to an `openai/` gateway
          # route and does not send it there). vLLM enforces it on the THINKING
          # field, not the reply — keep it generous; effort is the lever. SGLang
          # ignores it.
          extraBody:
            thinking_token_budget: 8192
"""

block = f"""{BEGIN}
  club:
    baseUrl: {gateway}
    apiKey: {key}
    api: openai-completions
    discovery:
      # Reads LiteLLM's /model_group/info: the live model list plus each route's
      # model_info (max_input_tokens, max_output_tokens, capabilities), which
      # scripts/lib/litellm-sync.sh renders from the serving engine on every switch.
      type: litellm
    compat:
      supportsDeveloperRole: false
      # Thinking on/off rides chat_template_kwargs.enable_thinking — the field vLLM,
      # SGLang and llama.cpp all read. (`qwen` would send a top-level enable_thinking
      # that vLLM and SGLang ignore, so omp's "off" level would silently keep thinking on.)
      thinkingFormat: qwen-chat-template
      # ...on chat completions. Through the gateway omp talks the Responses API
      # (`discovery: litellm`), where "off" used to send no `reasoning` field at all,
      # so the template's default (thinking on) still ran. This makes it send
      # `reasoning: {{effort: "none"}}`, which vLLM and SGLang both serve with no
      # reasoning. Upstream's answer to oh-my-pi#11184; checked through the gateway.
      reasoningDisableMode: none-effort
    modelOverrides:
{"".join(qwen38_override(m) for m in QWEN38_IDS)}{END}
"""

if print_only:
    print("providers:")
    print(block, end="")
    sys.exit(0)

os.makedirs(os.path.dirname(path), exist_ok=True)
text = io.open(path, encoding="utf-8").read() if os.path.exists(path) else ""
if BEGIN.strip() in text and END.strip() in text:
    pre, rest = text.split(BEGIN.strip(), 1)
    _, post = rest.split(END.strip(), 1)
    pre = pre.rstrip(" ")               # drop the old marker line's own indent
    new = pre + block + post.lstrip("\n")
    action = "refreshed"
elif re.search(r"^\s+club:\s*$", text, re.M) and BEGIN.strip() not in text:
    sys.exit("[omp-setup] models.yml already has a hand-written `club:` provider — "
             "rename or remove it, then re-run (this script only manages its own marked block).")
elif not text.strip():
    new = "providers:\n" + block
    action = "created"
elif re.search(r"^providers:\s*$", text, re.M):
    # models.yml's root holds only `providers:`, so the block can be appended at
    # the end of the file and still sit inside that mapping.
    new = text.rstrip("\n") + "\n" + block
    action = "added"
else:
    sys.exit("[omp-setup] models.yml has no top-level `providers:` key — not touching it.")

if text:                                # back up only when we are about to write
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    io.open(f"{path}.bak-{stamp}", "w", encoding="utf-8").write(text)
    print(f"[omp-setup] backed up {path} -> {path}.bak-{stamp}")
tmp = path + ".tmp"
io.open(tmp, "w", encoding="utf-8").write(new)
os.replace(tmp, path)
print(f"[omp-setup] {action} the `club` provider in {path}")
PY

[[ $PRINT -eq 1 ]] && exit 0

cat <<EOF

Next:
  1. Serve a model:   bash scripts/switch.sh --force vllm/qwen38-27b-dual-fast   (experimental; the slug docs/CODING_AGENTS.md recommends for agents)
  2. Check omp sees it with its real context window:
                      omp models club
  3. Add the local-GPU settings — this script never touches your config.yml:
     paste the block from docs/CODING_AGENTS.md ("Settings for ~/.omp/agent/config.yml")
     into ~/.omp/agent/config.yml, or load them per run:
                      omp --config "$ROOT_DIR/services/omp/omp-club.yml"
     ⚠️ Set modelRoles either way: with none, omp picks a model on its own from every
     gateway route, and a route you can't use can win.

  Optional: decode speed + prompt-cache share in the statusline:
                      cp "$ROOT_DIR/services/omp/extensions/tps-meter.ts" ~/.omp/agent/extensions/

  Always write models as club/<id> — a bare id can fuzzy-match a cloud provider.
  Scripted:  omp -p --model club/qwen3.8-27b --thinking low "..." </dev/null
EOF
if ! command -v omp >/dev/null 2>&1; then
  echo ""
  echo "  (omp is not on PATH — install it first: https://github.com/can1357/oh-my-pi)"
fi
