#!/usr/bin/env bash
# pi-setup.sh — point the pi coding agent at this rig's local models, through the
# LiteLLM gateway.
#
#   bash scripts/pi-setup.sh            # write/refresh the `club` provider, print the next steps
#   bash scripts/pi-setup.sh --print    # show the provider, change nothing
#   bash scripts/pi-setup.sh --gateway http://gateway-host:4000/v1   # a gateway on another box
#
# WHAT IT WRITES — the `club` provider in ~/.pi/agent/models.json (or
# $PI_CODING_AGENT_DIR/models.json). pi has no gateway discovery (omp does), so
# the model list is a SNAPSHOT: every route the gateway serves right now, with
# the context window it reports, plus `qwen3.8-27b` (the id every Qwen3.8 slug
# serves). Re-run it after switching to a slug with a different window or model.
# Other providers in the file are never touched; the old file is backed up.
#
# WHAT IT DOES NOT WRITE — your settings.json. Pick the model with /model (Ctrl+S
# saves it as the default) or `pi --model club/qwen3.8-27b`.
# docs/CODING_AGENTS.md ("pi — setup") explains each setting and what was measured.
#
# THE KEY — the gateway's LITELLM_MASTER_KEY from your club-3090 settings
# (~/.config/club-3090/secrets.env; `bash scripts/gateway-key.sh rotate` makes one),
# else the public default every install shares. LITELLM_MASTER_KEY set in the shell
# wins (a gateway on another box). After a rotate, re-run this script.
set -euo pipefail
export PYTHONUTF8="${PYTHONUTF8:-1}"
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

PRINT=0
GATEWAY="http://127.0.0.1:4000/v1"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --print) PRINT=1; shift ;;
    --gateway) GATEWAY="${2:?--gateway needs a URL}"; shift 2 ;;
    -h|--help) sed -n '2,23p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "pi-setup: unknown argument '$1' (see --help)" >&2; exit 2 ;;
  esac
done

AGENT_DIR="${PI_CODING_AGENT_DIR:-$HOME/.pi/agent}"
MODELS_JSON="$AGENT_DIR/models.json"
# The key through the one settings loader (#1466, #1467) — never read out of the
# compose file, whose line is `${LITELLM_MASTER_KEY:-…}` now, not the key.
# shellcheck source=lib/club-config.sh
. "$ROOT_DIR/scripts/lib/club-config.sh"
KEY="$(club_config_get LITELLM_MASTER_KEY "$ROOT_DIR" || true)"
KEY="${KEY:-sk-litellm-master-key}"   # the compose's default, when nothing is stored

python3 - "$MODELS_JSON" "$GATEWAY" "$KEY" "$PRINT" <<'PY'
import datetime, io, json, os, sys, urllib.request

path, gateway, key, print_only = sys.argv[1], sys.argv[2].rstrip("/"), sys.argv[3], sys.argv[4] == "1"
MARK = "club-3090 local models (generated by club-3090 scripts/pi-setup.sh; re-run to refresh)"

# Qwen3.8-family served ids — the same list as scripts/omp-setup.sh, which
# test-omp-setup checks against every name the composes serve (test-pi-setup
# keeps the two lists equal).
QWEN38_IDS = ["qwen3.8-27b", "qwen3.8-27b-fp8", "thinkingcap38-27b", "thinkingcap38-27b-fp8"]
ALWAYS = "qwen3.8-27b"      # every Qwen3.8 slug serves it, so it is listed even when nothing is up
FALLBACK_WINDOW = 262144    # the dual-fast slugs' window, for an id the gateway isn't serving now
REPLY_CAP = 32768           # thinking + answer; at most half the window on every Qwen3.8 slug

# The Qwen3.8 template takes reasoning_effort low | medium | xhigh (and DEFAULTS
# to xhigh when a request names none), so pi sends its level on every request as
# a template kwarg — the one field both vLLM and SGLang hand to the template.
# pi's own "high"/"max"/"minimal" have no counterpart: null hides them, and pi
# clamps a request for one to the nearest supported level.
QWEN38_COMPAT = {
    "thinkingFormat": "chat-template",
    "chatTemplateKwargs": {
        "enable_thinking": {"$var": "thinking.enabled"},
        "reasoning_effort": {"$var": "thinking.effort"},
    },
}
QWEN38_LEVELS = {"minimal": None, "low": "low", "medium": "medium", "high": None, "xhigh": "xhigh", "max": None}


def live_routes():
    """The gateway's routes that carry model_info (rendered from a serving engine)."""
    root = gateway[:-3] if gateway.endswith("/v1") else gateway
    req = urllib.request.Request(root + "/model_group/info", headers={"Authorization": f"Bearer {key}"})
    try:
        with urllib.request.urlopen(req, timeout=5) as r:
            data = json.load(r).get("data", [])
    except Exception as e:  # noqa: BLE001 — any failure means "no snapshot"
        print(f"[pi-setup] ⚠️  couldn't read {root}/model_group/info ({e.__class__.__name__}); "
              f"writing {ALWAYS} with a {FALLBACK_WINDOW:,}-token window — re-run with the slug up.",
              file=sys.stderr)
        return {}
    return {g["model_group"]: g for g in data if g.get("model_group") and g.get("max_input_tokens")}


def model(mid, route):
    m = {"id": mid, "name": f"{mid} (club-3090)",
         "contextWindow": int(route["max_input_tokens"]) if route else FALLBACK_WINDOW}
    if mid in QWEN38_IDS:
        m.update(reasoning=True, thinkingLevelMap=QWEN38_LEVELS, maxTokens=REPLY_CAP, compat=QWEN38_COMPAT)
    elif route:
        if route.get("max_output_tokens"):
            m["maxTokens"] = int(route["max_output_tokens"])
        m["reasoning"] = bool(route.get("supports_reasoning"))
    return m


routes = live_routes()
ids = [ALWAYS] + sorted(k for k in routes if k != ALWAYS)
provider = {
    "name": MARK,
    "baseUrl": gateway,
    "api": "openai-completions",
    "apiKey": key,
    # The Qwen3.8 template has no developer role, and pi's default is to fold any
    # later system message into the leading one (supportsMidConvoSystemMessages),
    # which keeps pi clear of the mid-conversation system-message 400 on vLLM.
    "compat": {"supportsDeveloperRole": False},
    "models": [model(mid, routes.get(mid)) for mid in ids],
}

if print_only:
    print(json.dumps({"providers": {"club": provider}}, indent=2, ensure_ascii=False))
    sys.exit(0)

os.makedirs(os.path.dirname(path), exist_ok=True)
text = io.open(path, encoding="utf-8").read() if os.path.exists(path) else ""
doc = json.loads(text) if text.strip() else {}
if not isinstance(doc, dict) or not isinstance(doc.setdefault("providers", {}), dict):
    sys.exit("[pi-setup] models.json has no top-level `providers` object — not touching it.")
old = doc["providers"].get("club")
if old is not None and old.get("name") != MARK:
    sys.exit("[pi-setup] models.json already has a hand-written `club` provider — "
             "rename or remove it, then re-run (this script only manages its own).")
action = "refreshed" if old is not None else ("added" if text.strip() else "created")
doc["providers"]["club"] = provider
new = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"

mode = os.stat(path).st_mode & 0o777 if text else 0o600   # the file holds API keys
if text:                                                   # back up only when about to write
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    bak = f"{path}.bak-{stamp}"
    io.open(bak, "w", encoding="utf-8").write(text)
    os.chmod(bak, mode)
    print(f"[pi-setup] backed up {path} -> {bak}")
tmp = path + ".tmp"
io.open(tmp, "w", encoding="utf-8").write(new)
os.chmod(tmp, mode)
os.replace(tmp, path)
print(f"[pi-setup] {action} the `club` provider in {path}: "
      + ", ".join(f"{m['id']} ({m['contextWindow']:,} ctx)" for m in provider["models"]))
PY

[[ $PRINT -eq 1 ]] && exit 0

cat <<EOF

Next:
  1. Serve a model:   bash scripts/switch.sh --force vllm/qwen38-27b-dual-fast   (experimental; the slug docs/CODING_AGENTS.md recommends for agents)
  2. Use it:          pi --model club/qwen3.8-27b     (or /model in pi — Ctrl+S saves it as the default)
     Thinking:        /thinking, or --thinking off|low|medium|xhigh
  3. Re-run this script after switching to a slug with a different context window
     or model — pi keeps the snapshot it was given.

  Optional: decode speed + prompt-cache share in the statusline:
                      cp "$ROOT_DIR/services/pi/extensions/tps-meter.ts" ~/.pi/agent/extensions/

  Scripted:  pi -p --model club/qwen3.8-27b --thinking low "..." </dev/null
EOF
if ! command -v pi >/dev/null 2>&1; then
  echo ""
  echo "  (pi is not on PATH — install it first: npm install -g @earendil-works/pi-coding-agent)"
fi
